include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: false

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    todo: ignore
