name: quantwealth
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  onboarding: ^4.0.2
  walletconnect_flutter_v2: ^2.2.3
  web3auth_flutter: ^3.1.7
  web3dart: ^2.7.3
  web3modal_flutter: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
