name: quantwealth
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.5
  eth_sig_util: ^0.0.9
  logger: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hex: ^0.2.0
  http: ^1.2.1
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  onboarding: ^4.0.2
  talker: ^4.2.0
  walletconnect_flutter_v2: ^2.2.3
  web3auth_flutter: ^3.1.7
  web3dart: ^2.7.3
  web3modal_flutter: ^3.1.3
  flutter_secure_storage: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: GalanoGrotesque
      fonts:
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueThin.otf
          weight: 100
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueExtraLight.otf
          weight: 200
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueLight.otf
          weight: 300
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueRegular.otf
          weight: 400
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueMedium.otf
          weight: 500
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueSemiBold.otf
          weight: 600
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueBold.otf
          weight: 700
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueExtraBold.otf
          weight: 800
        - asset: assets/fonts/GalanoGrotesque/GalanoGrotesqueBlack.otf
          weight: 900
